### ISSUE TITLE
代码发布了记得踢我一下

### ISSUE THREAD

**Issue by StarsTesla** [zju3dv/street_gaussians#1]

**Comment by pengsida** [comment]
We will release the code upon completion of the company's review process.

**Comment by TurtleZhong** [comment]
any updates? Really nice work!

> We will release the code upon completion of the company's review process.

**Comment by pengsida** [comment]
This is an unofficial implementation: https://github.com/LightwheelAI/street-gaussians-ns

**Comment by StarsTesla** [comment]
@pengsida 可以，我之前也做了一个复现，就是简单的pose优化加场景分解，效果还行，但是我感觉新视角还是不太好，你的版本好像pose有点抽搐（主页视频），我最开始也有，后来按照论文的学习率调了一下就很顺滑了，而且在一些视角不糊了

**Comment by yunzhiy** [comment]
Hi, the code has been released. I will update the README in a few days. Thanks for your interest and patience.
