### ISSUE TITLE
The reconstruction effectiveness for pedestrians 

### ISSUE THREAD

**Issue by mumianyuxin** [zju3dv/street_gaussians#11]
The dynamic objects modeling method introduced in the paper primarily focuses on vehicle. How about the effectiveness for pedestrian  and other categories?

**Comment by yunzhiy** [comment]
Currently our method is designed to handle rigid moving objects so the reconstruction of pedestrian may not be ideal. However, I think this problem can be efficiently solved by incorporating techniques like [4D Gaussian Splatting](https://github.com/hustvl/4DGaussians).
