### ISSUE TITLE
How did you combine SfM points and LiDAR points?

### ISSUE THREAD

**Issue by Lee-JaeWon** [zju3dv/street_gaussians#12]
Thank you for the good research. It was an impressive paper.

I'm curious about the contents of the paper, how did you combine LiDAR Points and SfM?

You can use the KITTI dataset to know the LiDAR points, coordinate system, and GT-Pose, but SfM does not know exactly the scale.

By the way, can I know how they combined?

I'd appreciate it if you could answer me.

**Comment by yunzhiy** [comment]
Hi, we obtain the SfM point cloud by treating camera poses as known parameters and perform point triangulation. In this way, the SfM and LiDAR points are all defined in the world coordinate system.
