### ISSUE TITLE
什么时候开源，期待

### ISSUE THREAD

**Issue by GeLink9999** [zju3dv/street_gaussians#13]

**Comment by zwlvd** [comment]
It seems to be a long time.

**Comment by TurtleZhong** [comment]
really nice work, any updates?

**Comment by pengsida** [comment]
This is an unofficial implementation: https://github.com/LightwheelAI/street-gaussians-ns

**Comment by zwlvd** [comment]
Will the official version be released?

**Comment by pengsida** [comment]
We are trying to pass the company's policy. 
I have read the unofficial implementation, which has very well reproduced the technical details of the paper.

**Comment by AmazingRoad** [comment]
@GeLink9999 Have released！
