### ISSUE TITLE
How to Obtain GS Matrices from Camera Parameters?

### ISSUE THREAD

**Issue by npurson** [zju3dv/street_gaussians#14]
Congratulations on your awesome work!

I come from a background in autonomous driving and am not familliar with graphic rendering. I'm confusing about transforming the camera intrinsics and extrinsics into the requisite `viewmatrix` and `projmatrix` for GS rasterization arguments.

It seems you might have already addressed in your work. Could you perhaps share some insights, tips, or point me in the right direction to achieve this successfully?

Thanks and looking forward to your valuable insights!

**Comment by yunzhiy** [comment]
1. `viewmatrix`: Viewmatrix can be obatined from extrinisic as shown in [here](https://github.com/graphdeco-inria/gaussian-splatting/blob/b17ded92b56ba02b6b7eaba2e66a2b0510f27764/utils/graphics_utils.py#L38).
2. `projmatrix`: The original 3D Gaussian assumes the principal point is located at the center of image plane. For general intrinsic of pinhole camera, you can refer to [this piece of code](https://github.com/skhu101/GauHuman/blob/85b2bfdf9091ca7c36d372ea2467f1e0b933f01b/utils/graphics_utils.py#L82).

**Comment by GG-Bonds** [comment]
> 1. `viewmatrix`: Viewmatrix can be obatined from extrinisic as shown in [here](https://github.com/graphdeco-inria/gaussian-splatting/blob/b17ded92b56ba02b6b7eaba2e66a2b0510f27764/utils/graphics_utils.py#L38).
> 2. `projmatrix`: The original 3D Gaussian assumes the principal point is located at the center of image plane. For general intrinsic of pinhole camera, you can refer to [this piece of code](https://github.com/skhu101/GauHuman/blob/85b2bfdf9091ca7c36d372ea2467f1e0b933f01b/utils/graphics_utils.py#L82).

I found that the principal point of nuscenes is not in the center. How did you modify this part?

**Comment by npurson** [comment]
> > 1. `viewmatrix`: Viewmatrix can be obatined from extrinisic as shown in [here](https://github.com/graphdeco-inria/gaussian-splatting/blob/b17ded92b56ba02b6b7eaba2e66a2b0510f27764/utils/graphics_utils.py#L38).
> > 2. `projmatrix`: The original 3D Gaussian assumes the principal point is located at the center of image plane. For general intrinsic of pinhole camera, you can refer to [this piece of code](https://github.com/skhu101/GauHuman/blob/85b2bfdf9091ca7c36d372ea2467f1e0b933f01b/utils/graphics_utils.py#L82).
> 
> I found that the principal point of nuscenes is not in the center. How did you modify this part?

It works for me to pad the image ensuring it centered
