### ISSUE TITLE
Some confusion about equation (2) in the paper

### ISSUE THREAD

**Issue by ShaohuaL** [zju3dv/street_gaussians#15]
Hello, if the $R_t$ means the Rotation from the object local coordinate system to the world coordinate system, why $R_w$ doesn't equal to $R_t R_o$ instead of $R_o R_t^T$ in the manuscript？Hoping for your reply！Thank you!
-----------------------------------
![image](https://github.com/zju3dv/street_gaussians/assets/50670138/83b09e51-ce41-4cbd-9e4d-533d8a24d62f)

**Comment by yunzhiy** [comment]
Hi, they are the same for reconstruction and novel view synthesis tasks as this is equivalent to learning inverse of the rotation.
