### ISSUE TITLE
dataset preparation

### ISSUE THREAD

**Issue by merriaux** [zju3dv/street_gaussians#17]
Hi,
Many thanks for your great work. Is it possible to have more details about dataset preparation ?
For example are you using as it camera to world transformations and intrinsics from waymo dataset or you ran colmap to refine it ?
thanks

**Comment by yunzhiy** [comment]
We use the camera pose from waymo dataset.  I have uploaded the preprocessed Waymo sequences [here](https://drive.google.com/file/d/1IJSFVGxwLLKLP8uidfUTGzb8n7nNDuIi/view), you can find more information in the README file of the dataset.

**Comment by TurtleZhong** [comment]
> We use the camera pose from waymo dataset. I have uploaded the preprocessed waymo sequences [here](https://drive.google.com/file/d/1IJSFVGxwLLKLP8uidfUTGzb8n7nNDuIi/view), you can find more information in the README file of the dataset.

Hi I found the dataset you uploaded only contain front image, can you upload a small preprocessed dataset that contain 3 view(front front-left and front-right), Thx!

**Comment by yunzhiy** [comment]
> > We use the camera pose from waymo dataset. I have uploaded the preprocessed waymo sequences [here](https://drive.google.com/file/d/1IJSFVGxwLLKLP8uidfUTGzb8n7nNDuIi/view), you can find more information in the README file of the dataset.
> 
> Hi I found the dataset you uploaded only contain front image, can you upload a small preprocessed dataset that contain 3 view(front front-left and front-right), Thx!

Sure，I will upload a multi-view dataset soon.

**Comment by merriaux** [comment]
Hi @yunzhiy , thanks for the sharing.
Did you undistort image at one point, because I didn't find distortion coefs in your zip file ?
thanks

**Comment by yunzhiy** [comment]
> Hi @yunzhiy , thanks for the sharing. Did you undistort images at one point, because I didn't find distortion coefs in your zip file ? thanks

We did not undistort the images following the setting of Emernerf here[https://github.com/NVlabs/EmerNeRF/blob/8c051d7cccbad3b52c7b11a519c971b8ead97e1a/datasets/waymo.py#L101](url) and we believe that this can be considered as a future improvement. Thanks for your suggestion.
