### ISSUE TITLE
evaluation about  optimizing tracked poses.

### ISSUE THREAD

**Issue by cv-lab-x** [zju3dv/street_gaussians#18]
hi, thanks for your great work, some questions about  optimizing tracked poses:
did you report the psnr on training views or test views with pose opt ?
if you report the psnr on test views, how did you align the training view poses after pose opt with test view poses, cause after pose opt.

Looking forward to your reply, @yunzhiy

**Comment by yunzhiy** [comment]
We report the psnr on test views. The object poses are obtained by interpolate between the two nearest training frames.
