### ISSUE TITLE
About the editing operations implements.

### ISSUE THREAD

**Issue by zwlvd** [zju3dv/street_gaussians#19]
It's really a great work. And I notice that Street Gaussian support various editing operations. How is the editing operations implemented？ How to separate so many dynamic objects in the scenes and edit them? It's a honor to get the answer.  @yunzhiy

**Comment by yunzhiy** [comment]
Since the Gaussians of object model is determined by the object tracklets, editing operations can be implemented by adjusting the object pose.

**Comment by zohairbadshah** [comment]
How were you able to achieve changing object color then? And would any change require retraining? On adding new objects, were you able to entirely new objects or just duplicate the existing one? Also, I noticed that the gaussians are loaded from model checkpoints, can they be loaded from the final ply file? It would be great if you could lay down steps for editing!
