### ISSUE TITLE
How do you manage such a large amount of Gaussians?

### ISSUE THREAD

**Issue by Cenbylin** [zju3dv/street_gaussians#20]
Thanks for the excellent work!

I am interested in how you handle the map. I assume there are a significant number of Gaussians for the entire scene background.

Did you render all the Gaussians, or divide them into blocks/bins?

**Comment by yunzhiy** [comment]
Although the number of Gaussians is significant for the entire scene, every time we only need to render Gaussians visible to current viewpoint.
