### ISSUE TITLE
What Sequences from Waymo were used?

### ISSUE THREAD

**Issue by skrya** [zju3dv/street_gaussians#21]
Dear Authors, 

Thanks for the amazing work!

May I know what were the 6 sequences used from waymo. It would be great if you can provide sequence number and frame start and end ids, if possible.

Thanks!

**Comment by yunzhiy** [comment]
We provide the preprocessed waymo sequences [here](https://drive.google.com/file/d/1IJSFVGxwLLKLP8uidfUTGzb8n7nNDuIi/view). Actually we have made some changes on the experiment settings, which will be updated in the next version of the paper.

**Comment by ucwxb** [comment]
> We provide the preprocessed waymo sequences [here](https://drive.google.com/file/d/1IJSFVGxwLLKLP8uidfUTGzb8n7nNDuIi/view). Actually we have made some changes on the experiment settings, which will be updated in the next version of the paper.

Hi Yunzhi,
I have downloaded the 8 sequences you've provieded. But there are only front views in each sequence. It seems not fair to compare street gaussian with baselines. In addition, the seletive sequences might not fully evaluate the performance of your work.

Thanks!

**Comment by yunzhiy** [comment]
> > We provide the preprocessed waymo sequences [here](https://drive.google.com/file/d/1IJSFVGxwLLKLP8uidfUTGzb8n7nNDuIi/view). Actually we have made some changes on the experiment settings, which will be updated in the next version of the paper.
> 
> Hi Yunzhi, I have downloaded the 8 sequences you've provieded. But there are only front views in each sequence. It seems not fair to compare street gaussian with baselines. In addition, the seletive sequences might not fully evaluate the performance of your work.
> 
> Thanks!

Hi, thanks for your interest. We follow our baselines Neural Scene Graph and Mars to evaluate on monocular videos. Our method can be extented to [multi-camera input](https://github.com/zju3dv/street_gaussians/issues/7#issuecomment-1899927705)  and we will update the dataset soon.

**Comment by FudongGe** [comment]
Hi,

Thanks for the amazing work!

I want to know if these numbers in the below pictures are the first few digits of the sequence numbers in the Waymo dataset. And are these eight sequences the ones used in the paper?

Thanks!

![image](https://github.com/user-attachments/assets/3dcc47d6-bc1a-4fba-98a0-ae2f8fbee130)
![image](https://github.com/user-attachments/assets/de288b91-4cef-4762-8e5c-5b371c5bd30f)

**Comment by yunzhiy** [comment]
Yes.
