### ISSUE TITLE
LPIPS version

### ISSUE THREAD

**Issue by tobiasfshr** [zju3dv/street_gaussians#22]
Hi, I am wondering which LPIPS version (VGG or AlexNet) you use for evaluation in Tab. 2 of your paper? Thanks!

**Comment by yunzhiy** [comment]
Hi, we use AlexNet as the backbone network of our LPIPS metric following [suds](https://github.com/hturki/suds/blob/9b472ad5e4fd4d810682af984ef65bfaf4d75188/suds/suds_model.py#L585).
