### ISSUE TITLE
result.json provided for castrack causes "No moving obj in current sequence"

### ISSUE THREAD

**Issue by ushio2021** [zju3dv/street_gaussians#33]
Hi,

Just wonder if the provided `result.json` for castrack has some issues, for instance, when processing 

- `segment-10448102132863604198_472_000_492_000_with_camera_labels`

in `waymo_converter.py`, the numpy array `valid` returned by the following lines seems to be always "all False",

https://github.com/zju3dv/street_gaussians/blob/ebff9c10d0ab8ea31dacd7d4ce426565f9385fc5/script/waymo/waymo_converter.py#L406-L410
which causes `track_camera_vis_castrack.json` has no valid data (also tracking results not visible in `track_vis_castrack.mp4`, but `track_vis.mp4` showed correct bboxes). As a result, `No moving obj in current sequence` showed during training.

Could you guys check it please or if I made some mistakes.

Thanks for this great work!

**Comment by yunzhiy** [comment]
Hi, there exists a bug in previous code. I have fixed it and you can try the script again. Thanks for pointing out the mistakes.
