### ISSUE TITLE
Google Drive Data Disappear

### ISSUE THREAD

**Issue by XChaoMeng** [zju3dv/street_gaussians#39]
Hello, I can’t open the link to the dataset. Could you please confirm if you have removed it from your Google Drive?

**Comment by yunzhiy** [comment]
I verified that the dataset is on Google drive. Could you please show me the link you are using?

**Comment by XChaoMeng** [comment]
Sorry, it was my mistake. I was using a proxy that couldn’t access Google Drive. I’ve changed to another proxy that can.
