### ISSUE TITLE
Pose from original dataset or pose from COLMAP?

### ISSUE THREAD

**Issue by yifanlu0227** [zju3dv/street_gaussians#4]
Great work! Street Gaussian proves the strong potential of 3DGS in reconstructing outdoor driving scenes.

I wonder whether the pose of each image comes from the original sensor calibration of the dataset, or is it recalibrated by COLMAP? Thank you!

**Comment by yunzhiy** [comment]
Hi, thanks for your interset. We use the pose from the sensor calibration of each dataset in our experiments.

**Comment by GANWANSHUI** [comment]
Thanks a lot for the great work! 

I wondering how to obtain ProjectionMatrix, directly use intrinsic from the sensor, or calculate from the FOV, thanks in advance if you can share details!

**Comment by yunzhiy** [comment]
We obtain ProjectionMatrix from intrinsic of the sensor, which requires minor changes of original 3D Gaussian code.

**Comment by GANWANSHUI** [comment]
Thank you for the reply. Would it be possible for you to share this piece of code or details so that I can begin the study with those datasets?  Thank you even though if infeasible.

**Comment by pengsida** [comment]
The code release need pass the company's review process. Thank you for your understanding.

**Comment by GANWANSHUI** [comment]
Sure, thank you!

**Comment by MatteoMarengo** [comment]
How the original ProjectionMatrix from 3DGS is modified ?
