### ISSUE TITLE
about pose optimization

### ISSUE THREAD

**Issue by zsy1987** [zju3dv/street_gaussians#5]
How do you get the Rt and Tt of the vehicle, according to the boundary box?
Will vehicle posture optimization in turn continue to affect the separation of the initial point cloud?

**Comment by yunzhiy** [comment]
1. Yes, the Rt and Tt of the vehicle is from the tracking boxes.
2. Vehicle pose optimization will not affect the separation of point cloud.

**Comment by zsy1987** [comment]
> 1. Yes, the Rt and Tt of the vehicle is from the tracking boxes.
> 2. Vehicle pose optimization will not affect the separation of point cloud.

Thank you for your answer. Will pose optimization affect the definition of object coordinate system?
